{% set name = "submission" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

channel:
  conda-forge

source:
  path: .

build:
  number: 0
  script: |
    {{ PYTHON }} -m grpc_tools.protoc -I. --python_out=submission --grpc_python_out=submission submission/server.proto
    {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - python
    - pip
    - setuptools
    - grpcio-tools
  host:
    - python
    - pip
    - setuptools
    - grpcio-tools
  run:
    - python
    - grpcio >=1.67.0
    - protobuf

test:
  imports:
    - submission
    - submission.server_pb2
    - submission.server_pb2_grpc

about:
  home: https://github.com/ECHO-HELLO-WORLD424/submission_client
  license: GPL
  summary: 'A package for job submission and monitoring'