{% set name = "submission_client" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

requirements:
  build:
    - python
    - setuptools
    - grpcio
    - grpcio-tools

  run:
    - python
    - grpcio
    - grpcio-tools


about:
  home: https://github.com/ECHO-HELLO-WORLD424/submission_client
  license: GPL v3.0
